/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProjectIdRouteImport } from './routes/_authenticated/$projectId'
import { Route as AuthenticatedProjectIdTimeRouteImport } from './routes/_authenticated/$projectId.time'
import { Route as AuthenticatedProjectIdSettingsRouteImport } from './routes/_authenticated/$projectId.settings'
import { Route as AuthenticatedProjectIdIssuesRouteImport } from './routes/_authenticated/$projectId.issues'
import { Route as AuthenticatedProjectIdInvoicesRouteImport } from './routes/_authenticated/$projectId.invoices'
import { Route as AuthenticatedProjectIdTimeIssueIdRouteImport } from './routes/_authenticated/$projectId.time.$issueId'
import { Route as AuthenticatedProjectIdIssuesIssueIdRouteImport } from './routes/_authenticated/$projectId.issues.$issueId'
import { Route as AuthenticatedProjectIdInvoicesInvoiceIdRouteImport } from './routes/_authenticated/$projectId.invoices.$invoiceId'
import { Route as AuthenticatedProjectIdInvoicesDraftDraftIdRouteImport } from './routes/_authenticated/$projectId.invoices.draft.$draftId'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectIdRoute = AuthenticatedProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectIdTimeRoute =
  AuthenticatedProjectIdTimeRouteImport.update({
    id: '/time',
    path: '/time',
    getParentRoute: () => AuthenticatedProjectIdRoute,
  } as any)
const AuthenticatedProjectIdSettingsRoute =
  AuthenticatedProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectIdRoute,
  } as any)
const AuthenticatedProjectIdIssuesRoute =
  AuthenticatedProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedProjectIdRoute,
  } as any)
const AuthenticatedProjectIdInvoicesRoute =
  AuthenticatedProjectIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedProjectIdRoute,
  } as any)
const AuthenticatedProjectIdTimeIssueIdRoute =
  AuthenticatedProjectIdTimeIssueIdRouteImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => AuthenticatedProjectIdTimeRoute,
  } as any)
const AuthenticatedProjectIdIssuesIssueIdRoute =
  AuthenticatedProjectIdIssuesIssueIdRouteImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => AuthenticatedProjectIdIssuesRoute,
  } as any)
const AuthenticatedProjectIdInvoicesInvoiceIdRoute =
  AuthenticatedProjectIdInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedProjectIdInvoicesRoute,
  } as any)
const AuthenticatedProjectIdInvoicesDraftDraftIdRoute =
  AuthenticatedProjectIdInvoicesDraftDraftIdRouteImport.update({
    id: '/draft/$draftId',
    path: '/draft/$draftId',
    getParentRoute: () => AuthenticatedProjectIdInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/progress': typeof ProgressRoute
  '/$projectId': typeof AuthenticatedProjectIdRouteWithChildren
  '/$projectId/invoices': typeof AuthenticatedProjectIdInvoicesRouteWithChildren
  '/$projectId/issues': typeof AuthenticatedProjectIdIssuesRouteWithChildren
  '/$projectId/settings': typeof AuthenticatedProjectIdSettingsRoute
  '/$projectId/time': typeof AuthenticatedProjectIdTimeRouteWithChildren
  '/$projectId/invoices/$invoiceId': typeof AuthenticatedProjectIdInvoicesInvoiceIdRoute
  '/$projectId/issues/$issueId': typeof AuthenticatedProjectIdIssuesIssueIdRoute
  '/$projectId/time/$issueId': typeof AuthenticatedProjectIdTimeIssueIdRoute
  '/$projectId/invoices/draft/$draftId': typeof AuthenticatedProjectIdInvoicesDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/progress': typeof ProgressRoute
  '/$projectId': typeof AuthenticatedProjectIdRouteWithChildren
  '/$projectId/invoices': typeof AuthenticatedProjectIdInvoicesRouteWithChildren
  '/$projectId/issues': typeof AuthenticatedProjectIdIssuesRouteWithChildren
  '/$projectId/settings': typeof AuthenticatedProjectIdSettingsRoute
  '/$projectId/time': typeof AuthenticatedProjectIdTimeRouteWithChildren
  '/$projectId/invoices/$invoiceId': typeof AuthenticatedProjectIdInvoicesInvoiceIdRoute
  '/$projectId/issues/$issueId': typeof AuthenticatedProjectIdIssuesIssueIdRoute
  '/$projectId/time/$issueId': typeof AuthenticatedProjectIdTimeIssueIdRoute
  '/$projectId/invoices/draft/$draftId': typeof AuthenticatedProjectIdInvoicesDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/progress': typeof ProgressRoute
  '/_authenticated/$projectId': typeof AuthenticatedProjectIdRouteWithChildren
  '/_authenticated/$projectId/invoices': typeof AuthenticatedProjectIdInvoicesRouteWithChildren
  '/_authenticated/$projectId/issues': typeof AuthenticatedProjectIdIssuesRouteWithChildren
  '/_authenticated/$projectId/settings': typeof AuthenticatedProjectIdSettingsRoute
  '/_authenticated/$projectId/time': typeof AuthenticatedProjectIdTimeRouteWithChildren
  '/_authenticated/$projectId/invoices/$invoiceId': typeof AuthenticatedProjectIdInvoicesInvoiceIdRoute
  '/_authenticated/$projectId/issues/$issueId': typeof AuthenticatedProjectIdIssuesIssueIdRoute
  '/_authenticated/$projectId/time/$issueId': typeof AuthenticatedProjectIdTimeIssueIdRoute
  '/_authenticated/$projectId/invoices/draft/$draftId': typeof AuthenticatedProjectIdInvoicesDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/progress'
    | '/$projectId'
    | '/$projectId/invoices'
    | '/$projectId/issues'
    | '/$projectId/settings'
    | '/$projectId/time'
    | '/$projectId/invoices/$invoiceId'
    | '/$projectId/issues/$issueId'
    | '/$projectId/time/$issueId'
    | '/$projectId/invoices/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/progress'
    | '/$projectId'
    | '/$projectId/invoices'
    | '/$projectId/issues'
    | '/$projectId/settings'
    | '/$projectId/time'
    | '/$projectId/invoices/$invoiceId'
    | '/$projectId/issues/$issueId'
    | '/$projectId/time/$issueId'
    | '/$projectId/invoices/draft/$draftId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/progress'
    | '/_authenticated/$projectId'
    | '/_authenticated/$projectId/invoices'
    | '/_authenticated/$projectId/issues'
    | '/_authenticated/$projectId/settings'
    | '/_authenticated/$projectId/time'
    | '/_authenticated/$projectId/invoices/$invoiceId'
    | '/_authenticated/$projectId/issues/$issueId'
    | '/_authenticated/$projectId/time/$issueId'
    | '/_authenticated/$projectId/invoices/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ProgressRoute: typeof ProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$projectId': {
      id: '/_authenticated/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$projectId/time': {
      id: '/_authenticated/$projectId/time'
      path: '/time'
      fullPath: '/$projectId/time'
      preLoaderRoute: typeof AuthenticatedProjectIdTimeRouteImport
      parentRoute: typeof AuthenticatedProjectIdRoute
    }
    '/_authenticated/$projectId/settings': {
      id: '/_authenticated/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedProjectIdRoute
    }
    '/_authenticated/$projectId/issues': {
      id: '/_authenticated/$projectId/issues'
      path: '/issues'
      fullPath: '/$projectId/issues'
      preLoaderRoute: typeof AuthenticatedProjectIdIssuesRouteImport
      parentRoute: typeof AuthenticatedProjectIdRoute
    }
    '/_authenticated/$projectId/invoices': {
      id: '/_authenticated/$projectId/invoices'
      path: '/invoices'
      fullPath: '/$projectId/invoices'
      preLoaderRoute: typeof AuthenticatedProjectIdInvoicesRouteImport
      parentRoute: typeof AuthenticatedProjectIdRoute
    }
    '/_authenticated/$projectId/time/$issueId': {
      id: '/_authenticated/$projectId/time/$issueId'
      path: '/$issueId'
      fullPath: '/$projectId/time/$issueId'
      preLoaderRoute: typeof AuthenticatedProjectIdTimeIssueIdRouteImport
      parentRoute: typeof AuthenticatedProjectIdTimeRoute
    }
    '/_authenticated/$projectId/issues/$issueId': {
      id: '/_authenticated/$projectId/issues/$issueId'
      path: '/$issueId'
      fullPath: '/$projectId/issues/$issueId'
      preLoaderRoute: typeof AuthenticatedProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AuthenticatedProjectIdIssuesRoute
    }
    '/_authenticated/$projectId/invoices/$invoiceId': {
      id: '/_authenticated/$projectId/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/$projectId/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedProjectIdInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedProjectIdInvoicesRoute
    }
    '/_authenticated/$projectId/invoices/draft/$draftId': {
      id: '/_authenticated/$projectId/invoices/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/$projectId/invoices/draft/$draftId'
      preLoaderRoute: typeof AuthenticatedProjectIdInvoicesDraftDraftIdRouteImport
      parentRoute: typeof AuthenticatedProjectIdInvoicesRoute
    }
  }
}

interface AuthenticatedProjectIdInvoicesRouteChildren {
  AuthenticatedProjectIdInvoicesInvoiceIdRoute: typeof AuthenticatedProjectIdInvoicesInvoiceIdRoute
  AuthenticatedProjectIdInvoicesDraftDraftIdRoute: typeof AuthenticatedProjectIdInvoicesDraftDraftIdRoute
}

const AuthenticatedProjectIdInvoicesRouteChildren: AuthenticatedProjectIdInvoicesRouteChildren =
  {
    AuthenticatedProjectIdInvoicesInvoiceIdRoute:
      AuthenticatedProjectIdInvoicesInvoiceIdRoute,
    AuthenticatedProjectIdInvoicesDraftDraftIdRoute:
      AuthenticatedProjectIdInvoicesDraftDraftIdRoute,
  }

const AuthenticatedProjectIdInvoicesRouteWithChildren =
  AuthenticatedProjectIdInvoicesRoute._addFileChildren(
    AuthenticatedProjectIdInvoicesRouteChildren,
  )

interface AuthenticatedProjectIdIssuesRouteChildren {
  AuthenticatedProjectIdIssuesIssueIdRoute: typeof AuthenticatedProjectIdIssuesIssueIdRoute
}

const AuthenticatedProjectIdIssuesRouteChildren: AuthenticatedProjectIdIssuesRouteChildren =
  {
    AuthenticatedProjectIdIssuesIssueIdRoute:
      AuthenticatedProjectIdIssuesIssueIdRoute,
  }

const AuthenticatedProjectIdIssuesRouteWithChildren =
  AuthenticatedProjectIdIssuesRoute._addFileChildren(
    AuthenticatedProjectIdIssuesRouteChildren,
  )

interface AuthenticatedProjectIdTimeRouteChildren {
  AuthenticatedProjectIdTimeIssueIdRoute: typeof AuthenticatedProjectIdTimeIssueIdRoute
}

const AuthenticatedProjectIdTimeRouteChildren: AuthenticatedProjectIdTimeRouteChildren =
  {
    AuthenticatedProjectIdTimeIssueIdRoute:
      AuthenticatedProjectIdTimeIssueIdRoute,
  }

const AuthenticatedProjectIdTimeRouteWithChildren =
  AuthenticatedProjectIdTimeRoute._addFileChildren(
    AuthenticatedProjectIdTimeRouteChildren,
  )

interface AuthenticatedProjectIdRouteChildren {
  AuthenticatedProjectIdInvoicesRoute: typeof AuthenticatedProjectIdInvoicesRouteWithChildren
  AuthenticatedProjectIdIssuesRoute: typeof AuthenticatedProjectIdIssuesRouteWithChildren
  AuthenticatedProjectIdSettingsRoute: typeof AuthenticatedProjectIdSettingsRoute
  AuthenticatedProjectIdTimeRoute: typeof AuthenticatedProjectIdTimeRouteWithChildren
}

const AuthenticatedProjectIdRouteChildren: AuthenticatedProjectIdRouteChildren =
  {
    AuthenticatedProjectIdInvoicesRoute:
      AuthenticatedProjectIdInvoicesRouteWithChildren,
    AuthenticatedProjectIdIssuesRoute:
      AuthenticatedProjectIdIssuesRouteWithChildren,
    AuthenticatedProjectIdSettingsRoute: AuthenticatedProjectIdSettingsRoute,
    AuthenticatedProjectIdTimeRoute:
      AuthenticatedProjectIdTimeRouteWithChildren,
  }

const AuthenticatedProjectIdRouteWithChildren =
  AuthenticatedProjectIdRoute._addFileChildren(
    AuthenticatedProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProjectIdRoute: typeof AuthenticatedProjectIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjectIdRoute: AuthenticatedProjectIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ProgressRoute: ProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
